unique_ids:
  assets:
    standard-page.html: PCZLPAI3VXNDVMLPLA4QLZAR7TFT36PL
    theme.css: 3EBPJ6N7B6NPQ4SYY7VVKTTMZSGU636H
  forms:
    Form1: XFR7G7ZZBLR5WNC3HFD33GYAU637BD53
  modules: {}
  scripts: {}
  server_modules: {}
